name: Dynamic Exit Code

on:
  workflow_dispatch:
    inputs:
      exit_code_to_use:
        description: 'The exit code to use (1-5).'
        required: true
        type: number
        default: "1"

jobs:
  dynamic-exit:
    runs-on: ubuntu-latest
    steps:
      - name: Check Input and Exit
        if: github.event.inputs.exit_code_to_use == '1'
        run: exit 1

      - name: Check Input and Exit
        if: github.event.inputs.exit_code_to_use == '2'
        run: exit 2

      - name: Check Input and Exit
        if: github.event.inputs.exit_code_to_use == '3'
        run: exit 3

      - name: Check Input and Exit
        if: github.event.inputs.exit_code_to_use == '4'
        run: exit 4

      - name: Check Input and Exit
        if: github.event.inputs.exit_code_to_use == '5'
        run: exit 5

      - name: Invalid Code
        if: github.event.inputs.exit_code_to_use != '1' && github.event.inputs.exit_code_to_use != '2' && github.event.inputs.exit_code_to_use != '3' && github.event.inputs.exit_code_to_use != '4' && github.event.inputs.exit_code_to_use != '5'
        run: |
          echo "Invalid exit code provided. Please use a number from 1 to 5."
          exit 100
