name: Get Tickets from PR Description

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  extract-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Body
        id: pr
        run: |
          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Extract Tickets
        shell: pwsh
        run: |
          $prBody = $env:PR_BODY
          Write-Host "PR Description: $prBody"

          $regex = '\[?(SE-\d+)\]\(https?://[^\)]+\)'
          $matches = [regex]::Matches($prBody, $regex)

          if ($matches.Count -gt 0) {
              $tickets = $matches | ForEach-Object { $_.Groups[1].Value }
              Write-Host "Tickets encontrados: $($tickets -join ', ')"

              $firstTicket = $tickets[0]
              Write-Host "Primer ticket encontrado: $firstTicket"
              echo "FIRST_TICKET=$firstTicket" >> $env:GITHUB_ENV
          } else {
              Write-Host "No se encontró ticket. Asignando 'none'."
              echo "FIRST_TICKET=none" >> $env:GITHUB_ENV
          }

      - name: Use Ticket
        run: echo "Usando el ticket $FIRST_TICKET"
