name: Test GitHub Context Values

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  test-context:
    runs-on: ubuntu-latest

    env:
      GITHUB_HEAD_REF: ${{ github.head_ref }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      # Use head_ref if it exists (PRs), otherwise fallback to ref_name
      BRANCH_NAME: ${{ github.head_ref != '' && github.head_ref || github.ref_name }}

    steps:
      - name: Print env values using Bash
        shell: bash
        run: |
          echo "Using Bash"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

      - name: Print env values using PowerShell
        shell: pwsh
        run: |
          Write-Host "Using PowerShell"
          Write-Host "GITHUB_HEAD_REF: $env:GITHUB_HEAD_REF"
          Write-Host "GITHUB_REF_NAME: $env:GITHUB_REF_NAME"

      - name: Show branch name in Bash
        shell: bash
        run: |
          echo "Using Bash:"
          echo "BRANCH_NAME is: $BRANCH_NAME"

      - name: Show branch name in PowerShell
        shell: pwsh
        run: |
          Write-Host "Using PowerShell:"
          Write-Host "BRANCH_NAME is: $env:BRANCH_NAME"
