name: Test GitHub Context Values

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  test-context:
    runs-on: ubuntu-latest

    env:
      GITHUB_HEAD_REF: ${{ github.head_ref }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      # Use head_ref if it exists (PRs), otherwise fallback to ref_name
      BRANCH_NAME: ${{ github.head_ref != '' && github.head_ref || github.ref_name }}

    steps:
      - name: Dump Pull Request GitHub Event to PowerShell Log
        shell: pwsh
        run: |
            # The github.event context is a JSON object. We use ConvertFrom-Json to parse it into a PowerShell object.
            $prEvent = @"
            ${{ toJSON(github.event) }}
            "@ | ConvertFrom-Json
            
            # 1. Print the entire event object (useful for debugging)
            Write-Host "--- Full PR Event Object ---"
            $prEvent | ConvertTo-Json -Depth 100 | Write-Host
            
            # Extract PR description
            $description = $prEvent.pull_request.body
             # Remove only quotes and backticks
            $cleanDescription = $description -replace '["''`]', ''
            Write-Host "--- Original Description ---"
            Write-Host $description
            Write-Host "`n--- Cleaned (Basic) Description ---"
            Write-Host $cleanDescription

    
      - name: Print env values using Bash
        shell: bash
        run: |
          echo "Using Bash"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

      - name: Print env values using PowerShell
        shell: pwsh
        run: |
          Write-Host "Using PowerShell"
          Write-Host "GITHUB_HEAD_REF: $env:GITHUB_HEAD_REF"
          Write-Host "GITHUB_REF_NAME: $env:GITHUB_REF_NAME"

      - name: Show branch name in Bash
        shell: bash
        run: |
          echo "Using Bash:"
          echo "BRANCH_NAME is: $BRANCH_NAME"

      - name: Show branch name in PowerShell
        shell: pwsh
        run: |
          Write-Host "Using PowerShell:"
          Write-Host "BRANCH_NAME is: $env:BRANCH_NAME"
